name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21

      - uses: gradle/actions/setup-gradle@v3
        with:
          arguments: assemble

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/**.jar

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21

      - uses: gradle/actions/setup-gradle@v3
        with:
          arguments: immaculateApply
          cache-read-only: true
